Algoritmo "ex5"

// Descrição   : Entrada valores reais e operações entre eles
// Autor(a)    : Luiz Felipe
// Data atual  : 26/12/2021
Var
n1, n2, soma, subt, mult, divisao : Real
Inicio
Escreva ("Digite um valor real: ")
Leia (n1)
Escreva ("Digite outro valor real: ")
Leia (n2)
soma <- n1+n2
subt <- n1-n2
mult <- n1*n2
divisao <- n1/n2
Escreval ("Soma= ", soma)
Escreval ("Subtração= ", subt)
Escreval ("Multiplicação= ", mult)
Escreval ("Divisão= ", divisao)
Fimalgoritmo