algoritmo "Exe_14_desafio"
var
   A, B, C : Inteiro
   S : Real
inicio
      Escreval ("Digite o primeiro valor inteiro: ")
      Leia (A)
      Escreval ("Digite o segundo valor inteiro: ")
      Leia (B)
      Escreval ("Digite o terceiro valor inteiro: ")
      Leia (C)
      S <- (A + B + C)^2
      Escreval (" O resultado do quadrado da soma dos três valores inteiros informados é : ", S)
      
fimalgoritmo